version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_rental           
      POSTGRES_USER: postgres           
      POSTGRES_PASSWORD: 1234           
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis
    container_name: redis
    networks:
      - superapp-network
    ports:
      - "6379:6379" 

networks:
  laravel:

volumes:
  dbdata:
