name: Laravel CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, tokenizer, xml
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Run Laravel config cache
      run: php artisan config:cache

    - name: Success message
      run: echo "🎉 Laravel CI completed successfully!"
